# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ccw335577
    url: jdbc:mysql://${MYSQL_HOST:rd.ccwcar.com}:${MYSQL_PORT:3306}/ccw_second_car?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
