server:
  port: 8848
  tomcat:
    basedir: logs

db:
  num: 1
  user: ${MYSQL-USER:root}
  password: ${MYSQL-PWD:ccw335577}
  url:
    0: jdbc:mysql://${MYSQL_HOST:rd.ccwcar.com}:${MYSQL_PORT:3306}/ccw_second_car?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

nacos:
  core:
    auth:
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql
  security:
    enabled: true

useAddressServer: true

